spring:
  application:
    name: PracticasAplicacion

  datasource:
    url: jdbc:postgresql://localhost:5432/practicas_tienda
    driver-class-name: org.postgresql.Driver
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    hikari:
      schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql


#
#
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql


#debug: true
