-- BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
-- INSERT INTO roles(id, nombre) VALUES (999, 'USER');
-- INSERT INTO usuarios(id, foto_id, roles_id, cedula, numero, apellidos, nombres, contrasena, correo, direccion) VALUES (100, null, 999, '1550212508', '0960279073', 'Herrera Guallo', 'Cristian Manuel', '{noop}12345678', 'cristianmherrera21@gmail.com', 'Arosemena Tola, Napo, Ecuador');
-- COMMIT;